name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy DaveBot
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}
                  username: ${{secrets.SSH_USER}}

                  script: |
                      sudo service davebot stop
                      rm -rf ~/davebot
                      git clone https://github.com/brimonk/DaveBot.git davebot
                      pushd davebot
                      npm i
                      echo "export BOT_TOKEN=${{secrets.BOT_TOKEN}}" > tokenset.sh
                      chmod +x tokenset.sh
                      . tokenset.sh
                      popd
                      sudo service davebot start

